#!/usr/bin/env bash

echo "Setting up ctags"

if ! hash ctags 2>/dev/null; then

    echo "Installing ctags"

    platform='unknown'
    unamestr=$(uname)
    if [[ "$unamestr" == 'Darwin' ]]; then
        if hash brew 1>&2>/dev/null; then
            brew install ctags
        elif hash port 1>&2>/dev/null; then
            port install ctags
        else
            echo "ERROR: I don't know what package manager you're using!"
            exit 1
        fi
    elif [[ "$unamestr" == 'Linux' ]]; then
        if hash apt-get 1>&2>/dev/null; then
            sudo apt-get -y install exuberant-ctags
        elif hash yum 1>&2>/dev/null; then
            sudo yum -y install ctags
        else
            echo "ERROR: I don't know what package manager you're using!"
            exit 1
        fi
    else
        echo "ERROR: I don't support installation for this OS yet!"
        exit 1
    fi

fi


