#!/bin/bash
set -e

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  echo "usage: dotf completions COMMAND [arg1 arg2...]" >&2
  exit 1
fi

COMMAND_PATH="$(command -v "dotf-$COMMAND")"
if grep -i "^# provide dotf completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
